- src/format_request.js
- src/get.js
- src/response_handler.js
- src/utils/field_format.js
- src/utils/field_reducer.js
- src/utils/group_concat.js
- src/utils/unwrap_field.js
- src/utils/validate_field.js
- src/utils/validate_label.js
- test/lib/sql-equal.js
- test/lib/sql-match.js
- test/specs/field_format.js
- test/specs/field_reducer.js
- test/specs/format_request.js
- test/specs/get-join.js
- test/specs/get-subquery.js
- test/specs/response_handler.js
- test/specs/unwrap_field.js
- test/specs/utils_group_concat.js
Utilise SQL Subquery syntax when getting results from external sources.
> Release 0.7: Subquery

- README.md
- package.json
- src/format_request.js
- src/response_handler.js
- src/table_handler.js
- src/utils/JSONparse.js
- test/specs/format_request.js
- test/specs/response_handler.js
- test/specs/table_handler.js
Add a replace before the parse, somebody put a tab in one of the field and JSON.parse could not handle that.
> Make JSON.parse safe, Escape characters, tab, newline etc

- .eslintrc.json
- src/format_request.js
- src/get.js
- src/index.js
- src/utils/error.js
- src/utils/unwrap_field.js
- src/utils/validate_field.js
- src/utils/validate_label.js
- test/specs/delete.js
- test/specs/format_request.js
- test/specs/get-join.js
- test/specs/get-subquery.js
- test/specs/get.js
- test/specs/init.js
- test/specs/patch.js
- test/specs/post.js
- test/specs/table_handler.js
Fixes 
#9 - Unique sql table alias
#1  - Stack trace in errors (partial fix)
> 0.9 Release - SQL Aliasing aliases + Stack Trace

- .gitignore
- README.md
- package.json
- src/format_request.js
- src/get.js
- src/index.js
- src/join_handler.js
- src/response_handler.js
- src/table_handler.js
- src/utils/error.js
- src/utils/field_reducer.js
- src/utils/format_datetime.js
- src/utils/group_concat.js
- test/specs/field_reducer.js
- test/specs/format_request.js
- test/specs/get-join.js
- test/specs/get.js
- test/specs/patch.js
- test/specs/post.js
- test/specs/response_handler.js
- test/specs/table_handler.js
- test/specs/utils_error.js
- test/specs/utils_format_datetime.js
> 100% Coverage

- README.md
- src/format_request.js
- src/get.js
- src/utils/field_reducer.js
- src/utils/field_relative.js
- src/utils/groupby_reducer.js
- src/utils/map_reduce.js
- src/utils/orderby_reducer.js
- src/utils/orderby_unwrap.js
- test/specs/field_reducer.js
- test/specs/format_request.js
- test/specs/get-join.js
- test/specs/get-subquery.js
- test/specs/get.js
- test/specs/groupby_reducer.js
- test/specs/orderby_reducer.js
- test/specs/orderby_unwrap.js
> orderby,groupby nested extras

- src/format_request.js
- src/get.js
- src/utils/field_format.js
- test/data/options.js
- test/specs/field_format.js
- test/specs/format_request.js
- test/specs/get-join.js
- test/specs/get-sort-group.js
- test/specs/get.js
> fix: orderby/groupby

- README.md
- src/utils/format_datetime.js
- test/specs/utils_format_datetime.js
Added the flexibility to handle `yyyy-mm-dd..dd` syntax, as well as `yyyy-m-d..d` and similar syntax by padding out single values.
> feat: alternate date syntax + date padding noissue

- package.json
> chore(package): update eslint-config-5app to version 0.2.1

- .circleci/config.yml
- CHANGELOG.md
- package.json
Semantic Release to ensure that releases to master bump the version, deploy to NPM and update a Changelog file.
> Implement semantic release

- README.md
- src/get.js
- src/index.js
- test/specs/get.js
- test/specs/getCount.js
Creates a new function `getCount` to retrieve the number of results which would have been obtained without a SQL `LIMIT` being applied.
> feat(getCount): New method to return the number of found records matching the request

- package.json
> chore(package): update eslint-config-5app to version 0.7.1

- README.md
- src/index.js
- src/utils/error.js
- src/utils/field_reducer.js
- test/data/options.js
- test/specs/field_reducer.js
- test/specs/get-datatypes.js
- test/specs/patch.js
- test/specs/post.js
Fixes #109 
Warning: This may break some patch operations as `JSON.stringify` was added 9 months ago 1725502 in v0.28 (although that was never official)
> feat(json): support serialised JSON data

- src/format_request.js
- test/specs/format_request.js
> feat(filter): filter empty, empty response, #92

- README.md
- src/response_handler.js
- test/specs/response_handler.js
Fixes #96
- Provides a means to format response
> feat(formatting): provide a means of formatting responses

- README.md
- src/index.js
- test/specs/delete.js
- test/specs/patch.js
Methods affected...
- `dare.patch`
- `dare.del`
Fixes #131
> feat(opt.notfound): adds opts.notfound, fixes #131

- src/utils/field_reducer.js
- test/specs/field_alias.js
- test/specs/field_reducer.js
> fix(alias): fix labelling of aliased fields

- src/format/join_handler.js
- src/format_request.js
- src/index.js
- src/join_handler.js
- test/specs/join_handler.js
Changes the way the join handler is invoked
> chore(refactor): join handler

- src/format/field_reducer.js
- src/response_handler.js
- test/specs/get-join.js
- test/specs/response_handler.js
fixes #150 
Removes extraneous fields added at the point of making generated fields.
> fix(generated-functions): remove extraneous fields

- README.md
- src/format/reducer_conditions.js
- src/format_request.js
- src/get.js
- src/index.js
- test/specs/get-join.js
> feat(filter): sql not exists

- README.md
- src/index.js
- test/specs/post.js
> feat: show more errors when duplicate_key='ignore' is set

- .circleci/config.yml
- package.json
- test/integration/.mocharc.json
- test/integration/data/schema.sql
- test/integration/docker-compose.yml
- test/integration/get.spec.js
- test/integration/helpers/db.js
- test/integration/mocha-hooks/index.js
- test/integration/mocha-hooks/mysql.js
- test/integration/run.sh
Initial MySQL Integration tests
> test(mysql): initiate mysql integration tests

- package.json
- src/format_request.js
- test/specs/format_request.js
> fix: throw error when calling format_request with falsy value

- src/get.js
- test/specs/get-subquery.spec.js
Fixes #242
Prevents repeated join conditions from appearing in the query
> fix(join): dont duplicate join conditions in subquery, fixes #242

- src/index.js
- test/specs/schema.defaultValue.spec.js
> fix(defaultValue): defaultValue in validateInput handler, fixes #249

- README.md
- src/format/field_reducer.js
- src/format/reducer_conditions.js
- src/index.js
- src/utils/unwrap_field.js
- test/specs/field_alias.spec.js
> feat(alias-sql): filter by an aliased field definition, #252

- src/utils/group_concat.js
- test/specs/get-subquery.spec.js
- test/specs/utils_group_concat.spec.js
fixes: #260
replace empty results with a NULL
> fix(group_concat): empty results NULL fixes #260

- .eslintrc.json
- CHANGELOG.md
- package-lock.json
- package.json
- src/format/join_handler.js
- src/format/reducer_conditions.js
- src/format_request.js
- src/get.js
- src/index.js
- src/utils/group_concat.js
- test/integration/get.spec.js
- test/integration/helpers/api.js
- test/integration/multi-table-modifications.spec.js
- test/specs/delete.spec.js
- test/specs/field_alias.spec.js
- test/specs/format_request.spec.js
- test/specs/get-join.spec.js
- test/specs/get-subquery.spec.js
- test/specs/get.spec.js
- test/specs/join_handler.spec.js
- test/specs/patch.spec.js
- test/specs/utils_group_concat.spec.js
> feat(next): Convert to use sql-template-tag

- .circleci/config.yml
- test/integration/run.sh
Tidies Node installation in CI
Uses Node 16.17.1
> chore(ci): use node orb

- src/format_request.js
- test/integration/multi-table-modifications.spec.js
> fix(patch/del): nested table handlers, fixes #277

- README.md
- src/format/join_handler.js
- src/format_request.js
- src/index.js
- src/utils/field_attributes.js
- test/specs/field_reducer.spec.js
- test/specs/schema.defaultValue.spec.js
> feat(fieldDefition): definition overrides by method, fixes #302

- src/format/reducer_conditions.js
- src/index.js
- test/data/options.js
- test/integration/binary.spec.js
- test/integration/data/schema.sql
- test/integration/helpers/api.js
Enables Buffer values to be used on SQL Binary fields
> feat(binary): support CRUD actions on Binary field types, noissue

- src/get.js
- test/integration/get.spec.js
- test/specs/get.spec.js
> feat(offset): Use explicit `OFFSET` syntax (not shorthand, i.e. `LIMIT <limit>, <offset>`)

- README.md
- src/index.js
- test/integration/get.spec.js
- test/specs/get.spec.js
Fixes #335 
feat(exists): easy way to determine whether a record exists
> feat(exists): easy way to determine whether a record exists

- README.md
- src/format/field_reducer.js
- src/index.js
- src/utils/field_attributes.js
- test/specs/field_access.spec.js
> feat(unknown-field-attr): define default attributes for unknown fields

- src/utils/unwrap_field.js
- test/specs/unwrap_field.spec.js
> feat(func-str-prefix): allow strings at beginning of function

- src/utils/field_attributes.js
> fix(anonymous-field-default): dont apply to _group and _count keywords

- CHANGELOG.md
- package-lock.json
- package.json
- src/get.js
- test/integration/disparities.spec.js
- test/integration/helpers/Postgres.js
- test/specs/get-subquery.spec.js
Workaround for MySQL 8.0 bug https://bugs.mysql.com/bug.php?id=109585
Fixes #382
> chore(release): Workaround MySQL8 bug

- src/format_request.js
- test/specs/format_request.spec.js
> fix(handler): enable handlers to attach filters to the request

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/format/reducer_conditions.js
- src/format_request.js
- src/get.js
- src/index.js
- src/utils/toArray.js
- test/integration/json.spec.js
- test/specs/filter_reducer.spec.js
- test/specs/format_request.spec.js
- test/specs/get-subquery.spec.js
- test/specs/patch.spec.js
Quite a significant performance change to SELECT queries with subqueries
> chore(release): 0.98.2
