5app/dare

README.md

Fix the typo on the name of the option `duplicate_keys` which can be used to ignore duplicate entries in a table when doing a bulk insert

docs: Fix the name of the option duplicate_keys

---

README.md

Replace `reqire` with `require` in the code snippet of how to include Dare in your project

docs: Fix typo in require

---

src/utils/field_reducer.js
test/specs/field_reducer.js

Fixes #36 
- Wraps fields defined as **`type: datetime`** with `DATE_FORMAT(${field},'%Y-%m-%dT%TZ')` casting them to an ISO datetime string. see https://stackoverflow.com/questions/9321809/format-date-in-mysql-select-as-iso-8601

fix(datetime): cast datetime fields in ISO format

---

src/utils/unwrap_field.js
test/specs/unwrap_field.js

- Allow `.` characters in function declarations. e.g. `DATE_FORMAT(field, "%Y-%m-%dT%T.%fZ")` (note the `.` to denote Milliseconds)
- Prevent lowercase strings in unquoted field values:
- Prevents values which could be interpolated as a table field e.g. `CONCAT(field, secret)`, where `secret` should not be accessible.
- `DATE_SUB(field, INTERVAL 1 DAY)` is ok as the mysql command `INTERVAL 1 DAY` is all in uppercase.
- `ROUND(field, 2)` is ok as the secondary value is just a number
- `IFNULL(field, "yes")` is ok because `yes` is quoted.

feat(field processing): define restrictions on field definitions

---

src/utils/JSONparse.js
test/specs/response_handler.js

Response Handler could not format values which were returned as `Buffer` objects. Not sure why integrations are returning Buffer. But resolved here nonetheless
```
TypeError: Cannot read property '0' of undefined
at label.split.forEach (src/response_handler.js:44:50)
at Array.forEach (<anonymous>)
at Dare.formatHandler (src/response_handler.js:42:21)
at Array.map (<anonymous>)
at Dare.responseHandler [as response_handler] (src/response_handler.js:9:14)
at Context.it (test/specs/response_handler.js:45:21)
```

fix(buffer): format response Buffer values

---

src/utils/field_reducer.js
test/specs/field_reducer.js
test/specs/get-join.js

Fixes #43
Does not override field values as it did before when a new one was an object.

fix: allow redefining arrays of field keys

---

src/format/field_reducer.js
src/format_request.js
src/get.js
src/index.js
src/response_handler.js
test/data/options.js
test/specs/field_reducer.js
test/specs/get-datatypes.js
test/specs/get-join.js
test/specs/response_handler.js

Dare didn't support deep nested generated fields more than a single depth, and then it also didn't work on arrays of items.
This PR fixes that and enables us to use generated fields in multiple places.

Fix nested generated fields

---

src/format_request.js
test/specs/get-sort-group.js

Includes the orderby and groupby conditions, where previously they were omitted when they were not required as part of a fields or filter.

fix(orderby/groupby): Ensures these joins are not cropped from the query #152

---

README.md
src/format/field_reducer.js
test/specs/field_reducer.js

Extend the schema field aliasing to allow defining fields on another table.
This will remove some of the complexity in the relational schema and provide a cleaner api interface.
e.g. In this example the user emails are in another table. In order to provide a simple way to get the email from the users model by calling `emailAddress`, we can use the alias prop to map to the `userEmail.email` model.field where that value resides. This will automatically join on that table using the join key. And return the value with prop key `emailAddress`.
```js
const dare = new Dare({
schema: {
users: {
emailAddress: {
// Explicitly define the alias
// Reference the email field on the usersEmails table.
// Plus: wrap in SQL formatting if so inclined.
alias: 'LOWER(usersEmails.email)'
}
},
// Any cross …
```

feat(alias): provide cross table field aliasing

---

README.md
src/index.js
test/specs/schema_override.js

Allow overriding the schema of the table we are overriding using `dare.post` and `dare.patch`.

feat: allow overriding the schema per operation

---

README.md
src/format/field_reducer.js
src/format/reducer_conditions.js
src/utils/validate_field.js
test/specs/field_reducer.js
test/specs/format_request.js
test/specs/get.js

Allows multiple **AND** conditions on the same key prop. 
e.g.  To create a search for a name where order is arbitrary, we need a query like `name LIKE '%Andrew%' AND name LIKE '%Dodson%'`. This was not possible before since object keys have to be unique.
note: Workaround were possible using aliasing fields, but that would change the schema and is non-scalable.
With suffixing (which is already used in tablenames) it is possible to make an field and filter key prop with an alternative value, So additional conditions can be added agains the same key.
e.g: Search for Strings in a _name_ field, when we're not sure of the order they occur...
```js
dare.get({
table: 'users',
fields: ['name'],
filter: {
name: '%Andrew%',
name$also: '%Dodson%',
}
});
// SELECT name FROM users WHERE name LIKE …
```

feat: ignore suffix on field property

---

src/response_handler.js
test/integration/data/schema.sql
test/integration/get.spec.js
test/specs/response_handler.js

Fixes bug which looks like 
```
1) response_handler
should given a field with an array of fields in the title split the values:
TypeError: Cannot read property '0' of undefined
at /Users/andrewdodson/workspace/dare/src/response_handler.js:18:182
at Array.forEach (<anonymous>)
at formatHandler (src/response_handler.js:18:66)
at /Users/andrewdodson/workspace/dare/src/response_handler.js:5:35
at Array.reduce (<anonymous>)
```
Although the line numbers are off, should read `at formatHandler (src/response_handler.js:79:21)`

fix(subquery): fix null subquery response

---

src/response_handler.js
test/specs/response_handler.js

Allows nested response objects to be defined with the suffixing marker `$`, 
i.e. Prior to this the model names with a `...$[suffix]` would have not have had their values expanded as expected
```diff
AssertionError: expected { Object (field, asset$planb.collection[id,name], ...) } to deeply equal { Object (field, asset, ...) }
+ expected
- actual
]
"id": 1
"name": "name"
}
-  "asset$planb.collection[id,name]": "[[\"1\",\"a\"],[\"2\",\"b\"]]"
+  "asset$planb": {
+    "collection": [
+      {
+        "id": "1"
+        "name": "a"
+      }
+      {
+        "id": "2"
+        "name": "b"
+      }
+    ]
+  }
"field": "value"
}
```

fix(suffixing): model names with $ in nested fields handling

---

src/format/field_reducer.js
src/response_handler.js
test/specs/get-join.js
test/specs/response_handler.js

Reenables a skipped test which allows us to reference nested generated field, e.g.
```
fields: {
"My Picture": "a_joined_model.a_gen_field"
}
```
Previously this would ignore the labelling and create an object. This PR resolves that.
TODO: Tidy this up an improve performance by moving some of the interpretation outside of the loop.

fix(generated): fix referencing a nested generated field

---

.github/workflows/nodejs.yml
README.md
src/format/join_handler.js
src/format_request.js
src/index.js
test/data/options.js
test/integration/get.spec.js
test/specs/after.js
test/specs/delete.js
test/specs/field_access.js
test/specs/field_alias.js
test/specs/format_request.js
test/specs/get-join.js
test/specs/get-subquery.js
test/specs/init.js
test/specs/join_handler.js
test/specs/patch.js
test/specs/post.js
test/specs/schema_override.js

This deprecates the `options.schema`, `options.table_alias`, `options[get|post|patch|delete]` handlers
And shifts these definitions. So they are logically grouped around a model.
```js
const myModelA = {
table, // this defines a mapping of a model to a SQL DB Table.
schema, // A schema object defining fields, as with options.schema, the schema is now grouped in with the model.
get, // Function to modify the request when accessing data
post, // Function to modify the request when posting data
patch, // Function to modify the request when patching data
del, // Function to modify the request when deleting data
};
dare.use({
models: {
myModelA,
// ... other model objects
}
});
```

feat(models): support for new options.models structure

---

src/index.js
test/specs/delete.js
test/specs/patch.js

#187
Temporarily ensure that deletes and patches do not use the unsupported nesting filters, otherwise this could lead to misleading actions.

fix(del, patch): throws an error is nested filter given, #187

---

README.md
src/utils/unwrap_field.js
test/specs/unwrap_field.js

Allow field definitions to be prefixable with negation operator `!`

feat(fields): fields prefixable with the negation operator

---

.circleci/config.yml
src/get.js
src/index.js
test/specs/field_alias.spec.js
test/specs/get-join.spec.js
test/specs/get-sort-group.spec.js
test/specs/get-subquery.spec.js
test/specs/init.spec.js
test/specs/sql.spec.js

Internally use `dare.sql({sql, values})` pattern
This could likely disrupt implementation tests where `dare.sql = overwritingFunction` is invoked

feat: refactor internal SQL function arguments

---

src/index.js
test/integration/get.spec.js
test/specs/field_alias.spec.js
test/specs/post.spec.js

Puts backticks (<code>`</code>) around field names when using the `duplicate_keys_update` option.
```sql
INSERT INTO ... ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `age`=VALUES(`age`)
```
Previously
```sql
INSERT INTO ... ON DUPLICATE KEY UPDATE name=VALUES(name), age=VALUES(age)
```

fix(duplicate_keys_update): put backticks around UPDATE fields

---

README.md
src/format/reducer_conditions.js
src/format_request.js
src/index.js
test/specs/format_request.spec.js

#182
- Supports `%` prefix in filter prop to infer the `LIKE` SQL comparison operator should be used.
- Provides a way to optionally disable/enable special characters in filter values to infer the comparison operator to use. For compatibility these are enabled, but shall be disabled in future versions.

feat(likey-filter): and flag to disable interpretted likey values

---

README.md
test/specs/unwrap_field.spec.js

#239
Documents the current caveat around multiple column references in field expressions.

docs(field_expressions): add caveat around multiple columns in field_expressions

---

src/utils/unwrap_field.js
test/specs/unwrap_field.spec.js

Supports in fields the following SQL
```js
[
'IF(field IS NULL, "yes", "no")',
'IF(field IS NOT NULL, "yes", "no")',
]
```

fix(sql): if field is null, conditional fields

---

src/format/field_reducer.js
src/format/groupby_reducer.js
src/format/orderby_reducer.js
src/utils/field_format.js
src/utils/unwrap_field.js
test/specs/format_request.spec.js
test/specs/get.spec.js

For #245 
In order to support INSERT...SELECT more practically. We need to be able to insert fixed values. To do that we need the `dare.get(..{fields[]})` to provide scalar values rather that define path to a field.
E.g.
```js
const resp = await dare.get({
table: 'test',
fields: [{
'show_100': 100,
'show_null': null,
'show_text': '"Text string 123"',
'show_function_text': 'CONCAT("Hello", "World")',
'name': 'name'
}],
filter: {id}
});
// SELECT 100 AS 'show_100', null AS 'show_null', "Text string 123" AS 'show_text', CONCAT("Hello", "World") AS 'show_function_text', a.name AS 'name' FROM test a WHERE a.id = ? LIMIT 1
```
This allows us to define non-field related result items, and wrt to INSERT...SELECT allows us to add a mix of query result data and new fields.

feat(fixed-field-values): i.e.  SELECT 123 AS myField... for #245

---

.eslintrc.json
.github/workflows/nodejs.yml
README.md
package.json
src/format_request.js
src/index.js
src/utils/field_attributes.js
test/specs/schema.defaultValue.spec.js

Implements #249
Defining the `defaultValue` introduces default conditions or values when querying or inserting records respectively.
`defaultValue` can be any value supported by the context it is used. If `defaultValue` is not an object, it will be applied to all operations, "methods" (`get`, `post`, `patch` and `del`). However when `defaultValue` is defined as an object, then the properties of the object matching the method will be used.
e.g we can define what `defaultValue` is used in various scenarios:
```js
defaultValue: {
get: 'active', // Includes `= 'active'` to `.get` filter conditions.
post: 'active', // Inserts `active` into new records
del: 'inactive', // Includes `= 'inactive'` to `.del` filter conditions.
// patch: is undefined and wont apply any default values
}
``` …

feat(defaultValues): support schema defaultValues in post, #249

---

README.md
src/format/field_reducer.js
src/index.js
src/response_handler.js
test/integration/helpers/db.js
test/integration/stream.spec.js
test/specs/get.spec.js
test/specs/init.spec.js
test/specs/response_handler.spec.js

Fixes #263
Provides a mechanism to 
- stream row data from DB source
- format a record item with the Dare response handler
- push to a custom handler defined by `rowHandler` (which maps to the legacy `response_row_handler`)
All without creating an internal Array of results, which can be memory expensive.
This should create a more efficient approach to handling lots of data through a Dare SELECT query.

feat(stream): support row streaming data from db

---

src/response_handler.js
test/integration/get.spec.js
test/specs/response_handler.spec.js

Fixes issue where `null` responses now being returned by JSON_ARRAY (as we no longer have to cast as a string) should be omitted if it's an empty object altogether.

fix(json-array): filtering empty nested joins

---

src/format/join_handler.js
test/specs/join_handler.spec.js

Prevents using the same field on a link table when using inferred intermediate joins.

fix(intermediate-table-join): field name conflict, #285

---

README.md
src/format/join_handler.js
test/integration/get.spec.js
test/integration/helpers/api.js
test/integration/modelAlias.spec.js
test/integration/shortcut_map.spec.js
test/specs/join_handler.spec.js

Fixes #285
Implement model shortcuts `models[model].shortcut_map : Map<>` provides a way to create deterministic shortcut routes to replace `infer_intermediate_joins` options.

feat(shortcuts): initial shortcuts support, fixes #285

---

README.md
src/format/field_reducer.js
src/format/join_handler.js
src/format/orderby_reducer.js
src/format/reducer_conditions.js
src/format_request.js
src/index.js
src/utils/field_attributes.js
test/data/options.js
test/integration/getFieldKey.spec.js
test/specs/schema.defaultValue.spec.js

Fixes #284
Defines a customisable function `options.getFieldKey` to map field names to names in the model schema.

feat(getFieldKey): interpret field names

---

src/utils/unwrap_field.js
test/specs/unwrap_field.spec.js

Adds support for a forward slash `/` within quotes on a field

fix(fields): allow forward slash within quotes, fixes 5app/hub#14234

---

README.md
src/format/join_handler.js
src/format/reducer_conditions.js
src/format_request.js
src/get.js
src/index.js
test/integration/data/schema.sql
test/integration/get.spec.js
test/specs/filter_reducer.spec.js

Fixes #324
Adds MySQL FullText syntax and cross field search capabilities
| Key        | Value                    | Type          | = SQL Condition                                                                                                                             |
| ---------- | ------------------------ | ------------- | ------------------------------------------------------------------------------------------------------------------------------------------- |
| \*text     | '+And\*'                 | Pattern       | `MATCH(text) AGAINST('+And*' IN BOOLEAN MODE)`                                                                                              |
| name,email | 'hello'                  | any           | `(name = 'hello' OR email = 'hello')` …

feat(fulltext): fulltext and cross-field search

---

src/format/reducer_conditions.js
src/index.js
test/integration/get.spec.js
test/specs/filter_reducer.spec.js
test/specs/fulltext_parser.spec.js

Parsers the FullText search text, ensuring common syntax mistakes are repaired
i.e.
- quoting inputs which use the `@` character, i.e. `email@example.com`, similarly hyphen `-` and apostrophe ','.
- removing spurious characters

fix(fulltext): parse input, quote incompatible strings, #324

---

src/index.js
test/specs/get_unique_alias.spec.js

Ensures we have human-readable characters within the generated SQL.

feat(tableAliases): use only alphabetical characters, noissue

---

src/utils/unwrap_field.js
test/specs/unwrap_field.spec.js

Supports new syntax to allow the `AS` in place of a comma (`,`).
i.e. `CAST(field AS SIGNED)`

feat(field_expression): support [FUNCNAME](field AS [UPPERCASE|String])
